baseURL = 'https://github.com/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[module]
    # uncomment line below for temporary local development of module
    # or when using a 'theme' as a git submodule
    replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false 
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false
    [[module.imports]]
        path = "./style.scss"
        disable = true 

[markup]
    [markup.tableOfContents]
      endLevel = 3
      startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # https://jdhao.github.io/2019/12/29/hugo_html_not_shown/
  # [markup.highlight]
  #   codeFences = false # disables Hugo's default syntax highlighting
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute] 
      block = true


        
[params]

  google_fonts = [
    ["Inter", "300, 400, 600, 700"],
    ["Fira Code", "500, 700"]
  ]

  sans_serif_font = "Inter"     # Default is System font
  secondary_font  = "Inter"     # Default is System font
  mono_font       = "Fira Code" # Default is System font




    [params.docs] # Parameters for the /docs 'template'
        title           = "Lotus Docs Example Site"           # default html title for documentation pages/sections

        pathName        = "docs"                            # path name for documentation site | default "docs"

        themeColor      = "blue"                            # (optional) - Set theme accent colour. Options include: blue (default), green, red, yellow, emerald, cardinal, magenta, cyan

        darkMode        = true                                # enable dark mode option? default false

        prism           = true                                # enable syntax highlighting via Prism

        prismTheme      = "lotusdocs"                           # (optional) - Set theme for PrismJS. Options include: lotusdocs (default), solarized-light, twilight, lucario

        # gitinfo
        repoBranch      = "release"

        sidebarIcons    = true                                # 目录前置图标
        breadcrumbs     = true                                # default is true
        backToTop       = true                                # 

        # ToC
        toc             = true                                # enable table of contents? default is true
        tocMobile       = true                                # enable table of contents in mobile view? default is true
        scrollSpy       = true                                # enable scrollspy on ToC? default is true

        # front matter
        descriptions    = false                                # enable front matter descriptions under content title?
        titleIcon       = false                                # enable front matter icon title prefix? default is false，文档中h1图标

        # content navigation
        navDesc         = false                                # include front matter descriptions in Prev/Next navigation cards
        navDescTrunc    = 30                                  # Number of characters by which to truncate the Prev/Next descriptions

        listDescTrunc   = 100                                 # Number of characters by which to truncate the list card description

        # Link behaviour
        intLinkTooltip  = true                                # Enable a tooltip for internal links that displays info about the destination? default false
        # extLinkNewTab   = false                             # Open external links in a new Tab? default true
        # logoLinkURL = ""                                    # Set a custom URL destination for the top header logo link.

    [params.flexsearch] # Parameters for FlexSearch
            enabled             = true
            # tokenize            = "full"
            # optimize            = true
            # cache               = 100
            # minQueryChar        = 3 # default is 0 (disabled)
            # maxResult           = 5 # default is 5
            # searchSectionsIndex = []

    [params.docsearch] # Parameters for DocSearch
        appID     = "7WE3B92RD7"                       # Algolia Application ID (or set env variable HUGO_PARAM_DOCSEARCH_appID)
        apiKey    = "a6fc80560087af46ddea2c8b4e3c1b52" # Algolia Search-Only API (Public) Key (or set env variable HUGO_PARAM_DOCSEARCH_apiKey)
        indexName = "memfire_doc"               # Index Name to perform search on (or set env variable HUGO_PARAM_DOCSEARCH_indexName)
    


[menu]
[[menu.primary]]
    name  = "文档"
    url = "/docs/"
    identifier = "docs"
    weight = 1
